#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cutting
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Alcimdb")]
	public partial class AlcimDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AlcimDBDataContext() : 
				base(global::Cutting.Properties.Settings.Default.AlcimdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlcimDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlcimDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlcimDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlcimDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fein_unit> fein_units
		{
			get
			{
				return this.GetTable<fein_unit>();
			}
		}
		
		public System.Data.Linq.Table<pool_teile> pool_teiles
		{
			get
			{
				return this.GetTable<pool_teile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fein_unit")]
	public partial class fein_unit
	{
		
		private string _sperrstation;
		
		private System.Nullable<System.DateTime> _sperrzeit;
		
		private string _lastmodstation;
		
		private System.Nullable<System.DateTime> _lastmodzeit;
		
		private int _auftnr;
		
		private short _pos;
		
		private short _u_pos;
		
		private int _teile_nr;
		
		private short _lfd_nummer;
		
		private string _etikettnr;
		
		private short _bde_flag;
		
		private short _serien_flag;
		
		private int _job;
		
		private int _typ;
		
		private int _los;
		
		private int _bock;
		
		private short _stapelnr;
		
		private short _sequenzbock;
		
		private short _sequenzlos;
		
		private int _lauf;
		
		private short _status;
		
		private int _menge;
		
		private int _split;
		
		private int _mirror;
		
		private int _muster;
		
		private int _bearb_nr;
		
		private short _fach_nr;
		
		private int _o_typ;
		
		private int _o_los;
		
		private int _o_bock;
		
		private short _o_stapelnr;
		
		private short _o_fach_nr;
		
		private short _o_sequenzbock;
		
		private short _o_sequenzlos;
		
		private int _together_kz;
		
		private int _los_flag;
		
		private int _buchungsmenge;
		
		private int _sequenztyp;
		
		private string _pmo_optiid;
		
		private int _pmo_rackid;
		
		private int _pmo_sequence;
		
		private int _dickendiff;
		
		private short _rotate;
		
		private int _pack_id;
		
		private int _spur;
		
		private int _spur_typ;
		
		private short _cutmirror;
		
		private int _pmg_index;
		
		private int _o_sequenztyp;
		
		private int _group_id;
		
		private double _plan_dauer;
		
		private double _plan_dauer_ur;
		
		private string _gruppenbc;
		
		private string _PARAM1;
		
		private string _PARAM2;
		
		private string _PARAM3;
		
		private string _PARAM4;
		
		private string _PARAM5;
		
		private int _orig_job;
		
		private int _orig_los;
		
		private int _orig_lfd;
		
		private int _orig_muster;
		
		private short _resolve_flag;
		
		private short _prodmirror;
		
		public fein_unit()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sperrstation", DbType="VarChar(6)")]
		public string sperrstation
		{
			get
			{
				return this._sperrstation;
			}
			set
			{
				if ((this._sperrstation != value))
				{
					this._sperrstation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sperrzeit", DbType="DateTime")]
		public System.Nullable<System.DateTime> sperrzeit
		{
			get
			{
				return this._sperrzeit;
			}
			set
			{
				if ((this._sperrzeit != value))
				{
					this._sperrzeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodstation", DbType="VarChar(6)")]
		public string lastmodstation
		{
			get
			{
				return this._lastmodstation;
			}
			set
			{
				if ((this._lastmodstation != value))
				{
					this._lastmodstation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodzeit", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodzeit
		{
			get
			{
				return this._lastmodzeit;
			}
			set
			{
				if ((this._lastmodzeit != value))
				{
					this._lastmodzeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftnr", DbType="Int NOT NULL")]
		public int auftnr
		{
			get
			{
				return this._auftnr;
			}
			set
			{
				if ((this._auftnr != value))
				{
					this._auftnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos", DbType="SmallInt NOT NULL")]
		public short pos
		{
			get
			{
				return this._pos;
			}
			set
			{
				if ((this._pos != value))
				{
					this._pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_pos", DbType="SmallInt NOT NULL")]
		public short u_pos
		{
			get
			{
				return this._u_pos;
			}
			set
			{
				if ((this._u_pos != value))
				{
					this._u_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teile_nr", DbType="Int NOT NULL")]
		public int teile_nr
		{
			get
			{
				return this._teile_nr;
			}
			set
			{
				if ((this._teile_nr != value))
				{
					this._teile_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfd_nummer", DbType="SmallInt NOT NULL")]
		public short lfd_nummer
		{
			get
			{
				return this._lfd_nummer;
			}
			set
			{
				if ((this._lfd_nummer != value))
				{
					this._lfd_nummer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etikettnr", DbType="VarChar(19)")]
		public string etikettnr
		{
			get
			{
				return this._etikettnr;
			}
			set
			{
				if ((this._etikettnr != value))
				{
					this._etikettnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bde_flag", DbType="SmallInt NOT NULL")]
		public short bde_flag
		{
			get
			{
				return this._bde_flag;
			}
			set
			{
				if ((this._bde_flag != value))
				{
					this._bde_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serien_flag", DbType="SmallInt NOT NULL")]
		public short serien_flag
		{
			get
			{
				return this._serien_flag;
			}
			set
			{
				if ((this._serien_flag != value))
				{
					this._serien_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="Int NOT NULL")]
		public int job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this._job = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="Int NOT NULL")]
		public int typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this._typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_los", DbType="Int NOT NULL")]
		public int los
		{
			get
			{
				return this._los;
			}
			set
			{
				if ((this._los != value))
				{
					this._los = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bock", DbType="Int NOT NULL")]
		public int bock
		{
			get
			{
				return this._bock;
			}
			set
			{
				if ((this._bock != value))
				{
					this._bock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stapelnr", DbType="SmallInt NOT NULL")]
		public short stapelnr
		{
			get
			{
				return this._stapelnr;
			}
			set
			{
				if ((this._stapelnr != value))
				{
					this._stapelnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequenzbock", DbType="SmallInt NOT NULL")]
		public short sequenzbock
		{
			get
			{
				return this._sequenzbock;
			}
			set
			{
				if ((this._sequenzbock != value))
				{
					this._sequenzbock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequenzlos", DbType="SmallInt NOT NULL")]
		public short sequenzlos
		{
			get
			{
				return this._sequenzlos;
			}
			set
			{
				if ((this._sequenzlos != value))
				{
					this._sequenzlos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lauf", DbType="Int NOT NULL")]
		public int lauf
		{
			get
			{
				return this._lauf;
			}
			set
			{
				if ((this._lauf != value))
				{
					this._lauf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt NOT NULL")]
		public short status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menge", DbType="Int NOT NULL")]
		public int menge
		{
			get
			{
				return this._menge;
			}
			set
			{
				if ((this._menge != value))
				{
					this._menge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_split", DbType="Int NOT NULL")]
		public int split
		{
			get
			{
				return this._split;
			}
			set
			{
				if ((this._split != value))
				{
					this._split = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mirror", DbType="Int NOT NULL")]
		public int mirror
		{
			get
			{
				return this._mirror;
			}
			set
			{
				if ((this._mirror != value))
				{
					this._mirror = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_muster", DbType="Int NOT NULL")]
		public int muster
		{
			get
			{
				return this._muster;
			}
			set
			{
				if ((this._muster != value))
				{
					this._muster = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_nr", DbType="Int NOT NULL")]
		public int bearb_nr
		{
			get
			{
				return this._bearb_nr;
			}
			set
			{
				if ((this._bearb_nr != value))
				{
					this._bearb_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fach_nr", DbType="SmallInt NOT NULL")]
		public short fach_nr
		{
			get
			{
				return this._fach_nr;
			}
			set
			{
				if ((this._fach_nr != value))
				{
					this._fach_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_typ", DbType="Int NOT NULL")]
		public int o_typ
		{
			get
			{
				return this._o_typ;
			}
			set
			{
				if ((this._o_typ != value))
				{
					this._o_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_los", DbType="Int NOT NULL")]
		public int o_los
		{
			get
			{
				return this._o_los;
			}
			set
			{
				if ((this._o_los != value))
				{
					this._o_los = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_bock", DbType="Int NOT NULL")]
		public int o_bock
		{
			get
			{
				return this._o_bock;
			}
			set
			{
				if ((this._o_bock != value))
				{
					this._o_bock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_stapelnr", DbType="SmallInt NOT NULL")]
		public short o_stapelnr
		{
			get
			{
				return this._o_stapelnr;
			}
			set
			{
				if ((this._o_stapelnr != value))
				{
					this._o_stapelnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_fach_nr", DbType="SmallInt NOT NULL")]
		public short o_fach_nr
		{
			get
			{
				return this._o_fach_nr;
			}
			set
			{
				if ((this._o_fach_nr != value))
				{
					this._o_fach_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_sequenzbock", DbType="SmallInt NOT NULL")]
		public short o_sequenzbock
		{
			get
			{
				return this._o_sequenzbock;
			}
			set
			{
				if ((this._o_sequenzbock != value))
				{
					this._o_sequenzbock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_sequenzlos", DbType="SmallInt NOT NULL")]
		public short o_sequenzlos
		{
			get
			{
				return this._o_sequenzlos;
			}
			set
			{
				if ((this._o_sequenzlos != value))
				{
					this._o_sequenzlos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_together_kz", DbType="Int NOT NULL")]
		public int together_kz
		{
			get
			{
				return this._together_kz;
			}
			set
			{
				if ((this._together_kz != value))
				{
					this._together_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_los_flag", DbType="Int NOT NULL")]
		public int los_flag
		{
			get
			{
				return this._los_flag;
			}
			set
			{
				if ((this._los_flag != value))
				{
					this._los_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buchungsmenge", DbType="Int NOT NULL")]
		public int buchungsmenge
		{
			get
			{
				return this._buchungsmenge;
			}
			set
			{
				if ((this._buchungsmenge != value))
				{
					this._buchungsmenge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequenztyp", DbType="Int NOT NULL")]
		public int sequenztyp
		{
			get
			{
				return this._sequenztyp;
			}
			set
			{
				if ((this._sequenztyp != value))
				{
					this._sequenztyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmo_optiid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string pmo_optiid
		{
			get
			{
				return this._pmo_optiid;
			}
			set
			{
				if ((this._pmo_optiid != value))
				{
					this._pmo_optiid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmo_rackid", DbType="Int NOT NULL")]
		public int pmo_rackid
		{
			get
			{
				return this._pmo_rackid;
			}
			set
			{
				if ((this._pmo_rackid != value))
				{
					this._pmo_rackid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmo_sequence", DbType="Int NOT NULL")]
		public int pmo_sequence
		{
			get
			{
				return this._pmo_sequence;
			}
			set
			{
				if ((this._pmo_sequence != value))
				{
					this._pmo_sequence = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dickendiff", DbType="Int NOT NULL")]
		public int dickendiff
		{
			get
			{
				return this._dickendiff;
			}
			set
			{
				if ((this._dickendiff != value))
				{
					this._dickendiff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rotate", DbType="SmallInt NOT NULL")]
		public short rotate
		{
			get
			{
				return this._rotate;
			}
			set
			{
				if ((this._rotate != value))
				{
					this._rotate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pack_id", DbType="Int NOT NULL")]
		public int pack_id
		{
			get
			{
				return this._pack_id;
			}
			set
			{
				if ((this._pack_id != value))
				{
					this._pack_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spur", DbType="Int NOT NULL")]
		public int spur
		{
			get
			{
				return this._spur;
			}
			set
			{
				if ((this._spur != value))
				{
					this._spur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spur_typ", DbType="Int NOT NULL")]
		public int spur_typ
		{
			get
			{
				return this._spur_typ;
			}
			set
			{
				if ((this._spur_typ != value))
				{
					this._spur_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cutmirror", DbType="SmallInt NOT NULL")]
		public short cutmirror
		{
			get
			{
				return this._cutmirror;
			}
			set
			{
				if ((this._cutmirror != value))
				{
					this._cutmirror = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmg_index", DbType="Int NOT NULL")]
		public int pmg_index
		{
			get
			{
				return this._pmg_index;
			}
			set
			{
				if ((this._pmg_index != value))
				{
					this._pmg_index = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_sequenztyp", DbType="Int NOT NULL")]
		public int o_sequenztyp
		{
			get
			{
				return this._o_sequenztyp;
			}
			set
			{
				if ((this._o_sequenztyp != value))
				{
					this._o_sequenztyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_id", DbType="Int NOT NULL")]
		public int group_id
		{
			get
			{
				return this._group_id;
			}
			set
			{
				if ((this._group_id != value))
				{
					this._group_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_dauer", DbType="Float NOT NULL")]
		public double plan_dauer
		{
			get
			{
				return this._plan_dauer;
			}
			set
			{
				if ((this._plan_dauer != value))
				{
					this._plan_dauer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_dauer_ur", DbType="Float NOT NULL")]
		public double plan_dauer_ur
		{
			get
			{
				return this._plan_dauer_ur;
			}
			set
			{
				if ((this._plan_dauer_ur != value))
				{
					this._plan_dauer_ur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gruppenbc", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string gruppenbc
		{
			get
			{
				return this._gruppenbc;
			}
			set
			{
				if ((this._gruppenbc != value))
				{
					this._gruppenbc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARAM1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PARAM1
		{
			get
			{
				return this._PARAM1;
			}
			set
			{
				if ((this._PARAM1 != value))
				{
					this._PARAM1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARAM2", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PARAM2
		{
			get
			{
				return this._PARAM2;
			}
			set
			{
				if ((this._PARAM2 != value))
				{
					this._PARAM2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARAM3", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PARAM3
		{
			get
			{
				return this._PARAM3;
			}
			set
			{
				if ((this._PARAM3 != value))
				{
					this._PARAM3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARAM4", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PARAM4
		{
			get
			{
				return this._PARAM4;
			}
			set
			{
				if ((this._PARAM4 != value))
				{
					this._PARAM4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARAM5", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PARAM5
		{
			get
			{
				return this._PARAM5;
			}
			set
			{
				if ((this._PARAM5 != value))
				{
					this._PARAM5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_job", DbType="Int NOT NULL")]
		public int orig_job
		{
			get
			{
				return this._orig_job;
			}
			set
			{
				if ((this._orig_job != value))
				{
					this._orig_job = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_los", DbType="Int NOT NULL")]
		public int orig_los
		{
			get
			{
				return this._orig_los;
			}
			set
			{
				if ((this._orig_los != value))
				{
					this._orig_los = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_lfd", DbType="Int NOT NULL")]
		public int orig_lfd
		{
			get
			{
				return this._orig_lfd;
			}
			set
			{
				if ((this._orig_lfd != value))
				{
					this._orig_lfd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_muster", DbType="Int NOT NULL")]
		public int orig_muster
		{
			get
			{
				return this._orig_muster;
			}
			set
			{
				if ((this._orig_muster != value))
				{
					this._orig_muster = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resolve_flag", DbType="SmallInt NOT NULL")]
		public short resolve_flag
		{
			get
			{
				return this._resolve_flag;
			}
			set
			{
				if ((this._resolve_flag != value))
				{
					this._resolve_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodmirror", DbType="SmallInt NOT NULL")]
		public short prodmirror
		{
			get
			{
				return this._prodmirror;
			}
			set
			{
				if ((this._prodmirror != value))
				{
					this._prodmirror = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pool_teile")]
	public partial class pool_teile
	{
		
		private string _sperrstation;
		
		private System.Nullable<System.DateTime> _sperrzeit;
		
		private string _lastmodstation;
		
		private System.Nullable<System.DateTime> _lastmodzeit;
		
		private int _auftnr;
		
		private short _pos;
		
		private short _u_pos;
		
		private int _teile_nr;
		
		private short _teile_ebene;
		
		private short _sl_tiefe;
		
		private short _auftkz;
		
		private System.Nullable<int> _oberteil_nr;
		
		private int _unterteil_max;
		
		private int _lauf;
		
		private int _verwend_lauf;
		
		private short _teile_kz;
		
		private short _freigabe_teil;
		
		private decimal _artnr;
		
		private int _glasart;
		
		private string _glasart_bez;
		
		private string _warengrp;
		
		private int _produktgrp;
		
		private int _breite;
		
		private int _hoehe;
		
		private int _dicke;
		
		private short _menge;
		
		private string _artbez1;
		
		private string _artbez2;
		
		private string _kurz_bez;
		
		private int _etikett_kz;
		
		private string _etikettnr_start;
		
		private short _prioritaet;
		
		private string _typen_vektor;
		
		private int _einbautiefe;
		
		private System.DateTime _prod_term;
		
		private short _ausgangsnr;
		
		private int _ausgangsbock;
		
		private short _bestell_flag;
		
		private short _sonder_kz1;
		
		private short _sonder_kz2;
		
		private string _linie;
		
		private short _bearb_kz;
		
		private short _struktur_typ;
		
		private short _struktur_pos;
		
		private short _beschicht_pos;
		
		private short _beschicht_typ;
		
		private short _modell_nr;
		
		private short _stufen_flag;
		
		private short _korrektur_flag;
		
		private short _teilfert_kz;
		
		private short _serien_kz;
		
		private short _opti_flag;
		
		private short _text_flag;
		
		private short _uebermenge_kz;
		
		private short _prodmenge;
		
		private short _austausch_kz;
		
		private short _auftragsmenge;
		
		private System.Nullable<short> _otyp;
		
		private string _utyp;
		
		private short _modell_gruppe;
		
		private short _modell_flag;
		
		private short _sprossen_flag;
		
		private short _logo_nr;
		
		private short _logo_lage;
		
		private short _o_giessharz_flag;
		
		private short _o_esg_flag;
		
		private short _o_vsg_flag;
		
		private short _o_iso_flag;
		
		private short _u_giessharz_flag;
		
		private short _u_esg_flag;
		
		private short _u_vsg_flag;
		
		private short _u_bestell_flag;
		
		private short _t_giessharz_flag;
		
		private short _t_esg_flag;
		
		private short _t_vsg_flag;
		
		private short _t_iso_flag;
		
		private string _param1;
		
		private string _param2;
		
		private string _param3;
		
		private string _param4;
		
		private string _param5;
		
		private string _param6;
		
		private string _param7;
		
		private string _param8;
		
		private string _param9;
		
		private string _param10;
		
		private short _status;
		
		private System.DateTime _statuszeit;
		
		private short _beschaffungsart;
		
		private string _ae_referenz;
		
		private string _sondertext1;
		
		private string _sondertext2;
		
		private string _sondertext3;
		
		private string _sondertext4;
		
		private string _sondertext5;
		
		private string _artikel_extra1;
		
		private string _artikel_extra2;
		
		private short _sonder_kz3;
		
		private short _logo_seite;
		
		private string _lager;
		
		private int _auftragsdicke;
		
		private short _ttyp;
		
		private string _b_klasse1_text;
		
		private string _b_klasse2_text;
		
		private string _b_klasse3_text;
		
		private string _b_klasse4_text;
		
		private string _b_klasse5_text;
		
		private string _b_klasse6_text;
		
		private string _b_klasse7_text;
		
		private string _b_klasse8_text;
		
		private short _o_tvg_flag;
		
		private decimal _beschicht1_artnr;
		
		private int _beschicht1_masch;
		
		private double _beschicht1_kapa;
		
		private short _beschicht1_pos;
		
		private short _beschicht1_typ;
		
		private string _beschicht1_ctrl;
		
		private decimal _beschicht2_artnr;
		
		private int _beschicht2_masch;
		
		private double _beschicht2_kapa;
		
		private short _beschicht2_pos;
		
		private short _beschicht2_typ;
		
		private string _beschicht2_ctrl;
		
		private int _laufweg;
		
		private int _bearbfolge;
		
		private int _mzo_id_phys_1;
		
		private int _mzo_id_es_1;
		
		private int _mzo_technologie1_1;
		
		private int _mzo_id_phys_2;
		
		private int _mzo_id_es_2;
		
		private int _mzo_technologie1_2;
		
		private int _mzo_id_phys_3;
		
		private short _u_tvg_flag;
		
		private short _t_tvg_flag;
		
		private System.DateTime _prod_start;
		
		private double _flaeche;
		
		private int _los_flag;
		
		private short _sonderglas;
		
		private short _sonderglas_freigab;
		
		private int _etikett_art;
		
		private int _etikettnr_count;
		
		private int _skizzen_art;
		
		private short _routelog_id1;
		
		private short _routelog_id2;
		
		private short _routelog_id3;
		
		private short _part_fixed;
		
		private int _mzo_id_es_3;
		
		private int _mzo_technologie1_3;
		
		private int _rahmenskizzen_art;
		
		private int _bearb_anz;
		
		private double _bearb_dauer;
		
		private int _bearbtiefe_anz;
		
		private double _bearbtiefe_dauer;
		
		private int _bearbfertig_anz;
		
		private double _bearbfertig_dauer;
		
		private string _auftnr_pos;
		
		private int _scheibnr_u_oteil;
		
		private int _teilnr_u_oteil;
		
		private int _stklistentiefe;
		
		private int _anz_bearb;
		
		private short _etiketten_erzeugt;
		
		private short _skizzen_erzeugt;
		
		private short _rskizzen_erzeugt;
		
		private string _cu_id;
		
		private short _beschaffungsart0;
		
		private string _entschicht_id;
		
		private string _bestell_id;
		
		private short _bdefertig;
		
		private short _bdestueckoffen_anz;
		
		private short _bdebearb_anz;
		
		private int _beschich;
		
		private int _stufen_ref;
		
		private int _glas_id;
		
		private int _glas_id10;
		
		private short _vielfachheit;
		
		private short _spalten;
		
		private int _bde_serie;
		
		private int _mindermenge;
		
		private int _menge_nach;
		
		private int _mindermenge_nach;
		
		private short _freigabe_teil0;
		
		private short _merke_beschaffung;
		
		private double _gewicht_rechteck;
		
		private int _lieferant;
		
		public pool_teile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sperrstation", DbType="VarChar(6)")]
		public string sperrstation
		{
			get
			{
				return this._sperrstation;
			}
			set
			{
				if ((this._sperrstation != value))
				{
					this._sperrstation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sperrzeit", DbType="DateTime")]
		public System.Nullable<System.DateTime> sperrzeit
		{
			get
			{
				return this._sperrzeit;
			}
			set
			{
				if ((this._sperrzeit != value))
				{
					this._sperrzeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodstation", DbType="VarChar(6)")]
		public string lastmodstation
		{
			get
			{
				return this._lastmodstation;
			}
			set
			{
				if ((this._lastmodstation != value))
				{
					this._lastmodstation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodzeit", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodzeit
		{
			get
			{
				return this._lastmodzeit;
			}
			set
			{
				if ((this._lastmodzeit != value))
				{
					this._lastmodzeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftnr", DbType="Int NOT NULL")]
		public int auftnr
		{
			get
			{
				return this._auftnr;
			}
			set
			{
				if ((this._auftnr != value))
				{
					this._auftnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos", DbType="SmallInt NOT NULL")]
		public short pos
		{
			get
			{
				return this._pos;
			}
			set
			{
				if ((this._pos != value))
				{
					this._pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_pos", DbType="SmallInt NOT NULL")]
		public short u_pos
		{
			get
			{
				return this._u_pos;
			}
			set
			{
				if ((this._u_pos != value))
				{
					this._u_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teile_nr", DbType="Int NOT NULL")]
		public int teile_nr
		{
			get
			{
				return this._teile_nr;
			}
			set
			{
				if ((this._teile_nr != value))
				{
					this._teile_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teile_ebene", DbType="SmallInt NOT NULL")]
		public short teile_ebene
		{
			get
			{
				return this._teile_ebene;
			}
			set
			{
				if ((this._teile_ebene != value))
				{
					this._teile_ebene = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl_tiefe", DbType="SmallInt NOT NULL")]
		public short sl_tiefe
		{
			get
			{
				return this._sl_tiefe;
			}
			set
			{
				if ((this._sl_tiefe != value))
				{
					this._sl_tiefe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftkz", DbType="SmallInt NOT NULL")]
		public short auftkz
		{
			get
			{
				return this._auftkz;
			}
			set
			{
				if ((this._auftkz != value))
				{
					this._auftkz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oberteil_nr", DbType="Int")]
		public System.Nullable<int> oberteil_nr
		{
			get
			{
				return this._oberteil_nr;
			}
			set
			{
				if ((this._oberteil_nr != value))
				{
					this._oberteil_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unterteil_max", DbType="Int NOT NULL")]
		public int unterteil_max
		{
			get
			{
				return this._unterteil_max;
			}
			set
			{
				if ((this._unterteil_max != value))
				{
					this._unterteil_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lauf", DbType="Int NOT NULL")]
		public int lauf
		{
			get
			{
				return this._lauf;
			}
			set
			{
				if ((this._lauf != value))
				{
					this._lauf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verwend_lauf", DbType="Int NOT NULL")]
		public int verwend_lauf
		{
			get
			{
				return this._verwend_lauf;
			}
			set
			{
				if ((this._verwend_lauf != value))
				{
					this._verwend_lauf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teile_kz", DbType="SmallInt NOT NULL")]
		public short teile_kz
		{
			get
			{
				return this._teile_kz;
			}
			set
			{
				if ((this._teile_kz != value))
				{
					this._teile_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freigabe_teil", DbType="SmallInt NOT NULL")]
		public short freigabe_teil
		{
			get
			{
				return this._freigabe_teil;
			}
			set
			{
				if ((this._freigabe_teil != value))
				{
					this._freigabe_teil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artnr", DbType="Decimal(12,0) NOT NULL")]
		public decimal artnr
		{
			get
			{
				return this._artnr;
			}
			set
			{
				if ((this._artnr != value))
				{
					this._artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glasart", DbType="Int NOT NULL")]
		public int glasart
		{
			get
			{
				return this._glasart;
			}
			set
			{
				if ((this._glasart != value))
				{
					this._glasart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glasart_bez", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string glasart_bez
		{
			get
			{
				return this._glasart_bez;
			}
			set
			{
				if ((this._glasart_bez != value))
				{
					this._glasart_bez = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warengrp", DbType="VarChar(6)")]
		public string warengrp
		{
			get
			{
				return this._warengrp;
			}
			set
			{
				if ((this._warengrp != value))
				{
					this._warengrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produktgrp", DbType="Int NOT NULL")]
		public int produktgrp
		{
			get
			{
				return this._produktgrp;
			}
			set
			{
				if ((this._produktgrp != value))
				{
					this._produktgrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_breite", DbType="Int NOT NULL")]
		public int breite
		{
			get
			{
				return this._breite;
			}
			set
			{
				if ((this._breite != value))
				{
					this._breite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoehe", DbType="Int NOT NULL")]
		public int hoehe
		{
			get
			{
				return this._hoehe;
			}
			set
			{
				if ((this._hoehe != value))
				{
					this._hoehe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dicke", DbType="Int NOT NULL")]
		public int dicke
		{
			get
			{
				return this._dicke;
			}
			set
			{
				if ((this._dicke != value))
				{
					this._dicke = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menge", DbType="SmallInt NOT NULL")]
		public short menge
		{
			get
			{
				return this._menge;
			}
			set
			{
				if ((this._menge != value))
				{
					this._menge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artbez1", DbType="VarChar(30)")]
		public string artbez1
		{
			get
			{
				return this._artbez1;
			}
			set
			{
				if ((this._artbez1 != value))
				{
					this._artbez1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artbez2", DbType="VarChar(30)")]
		public string artbez2
		{
			get
			{
				return this._artbez2;
			}
			set
			{
				if ((this._artbez2 != value))
				{
					this._artbez2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurz_bez", DbType="VarChar(30)")]
		public string kurz_bez
		{
			get
			{
				return this._kurz_bez;
			}
			set
			{
				if ((this._kurz_bez != value))
				{
					this._kurz_bez = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etikett_kz", DbType="Int NOT NULL")]
		public int etikett_kz
		{
			get
			{
				return this._etikett_kz;
			}
			set
			{
				if ((this._etikett_kz != value))
				{
					this._etikett_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etikettnr_start", DbType="VarChar(19)")]
		public string etikettnr_start
		{
			get
			{
				return this._etikettnr_start;
			}
			set
			{
				if ((this._etikettnr_start != value))
				{
					this._etikettnr_start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioritaet", DbType="SmallInt NOT NULL")]
		public short prioritaet
		{
			get
			{
				return this._prioritaet;
			}
			set
			{
				if ((this._prioritaet != value))
				{
					this._prioritaet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typen_vektor", DbType="VarChar(10)")]
		public string typen_vektor
		{
			get
			{
				return this._typen_vektor;
			}
			set
			{
				if ((this._typen_vektor != value))
				{
					this._typen_vektor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_einbautiefe", DbType="Int NOT NULL")]
		public int einbautiefe
		{
			get
			{
				return this._einbautiefe;
			}
			set
			{
				if ((this._einbautiefe != value))
				{
					this._einbautiefe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_term", DbType="DateTime NOT NULL")]
		public System.DateTime prod_term
		{
			get
			{
				return this._prod_term;
			}
			set
			{
				if ((this._prod_term != value))
				{
					this._prod_term = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ausgangsnr", DbType="SmallInt NOT NULL")]
		public short ausgangsnr
		{
			get
			{
				return this._ausgangsnr;
			}
			set
			{
				if ((this._ausgangsnr != value))
				{
					this._ausgangsnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ausgangsbock", DbType="Int NOT NULL")]
		public int ausgangsbock
		{
			get
			{
				return this._ausgangsbock;
			}
			set
			{
				if ((this._ausgangsbock != value))
				{
					this._ausgangsbock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bestell_flag", DbType="SmallInt NOT NULL")]
		public short bestell_flag
		{
			get
			{
				return this._bestell_flag;
			}
			set
			{
				if ((this._bestell_flag != value))
				{
					this._bestell_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonder_kz1", DbType="SmallInt NOT NULL")]
		public short sonder_kz1
		{
			get
			{
				return this._sonder_kz1;
			}
			set
			{
				if ((this._sonder_kz1 != value))
				{
					this._sonder_kz1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonder_kz2", DbType="SmallInt NOT NULL")]
		public short sonder_kz2
		{
			get
			{
				return this._sonder_kz2;
			}
			set
			{
				if ((this._sonder_kz2 != value))
				{
					this._sonder_kz2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linie", DbType="VarChar(13)")]
		public string linie
		{
			get
			{
				return this._linie;
			}
			set
			{
				if ((this._linie != value))
				{
					this._linie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_kz", DbType="SmallInt NOT NULL")]
		public short bearb_kz
		{
			get
			{
				return this._bearb_kz;
			}
			set
			{
				if ((this._bearb_kz != value))
				{
					this._bearb_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_struktur_typ", DbType="SmallInt NOT NULL")]
		public short struktur_typ
		{
			get
			{
				return this._struktur_typ;
			}
			set
			{
				if ((this._struktur_typ != value))
				{
					this._struktur_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_struktur_pos", DbType="SmallInt NOT NULL")]
		public short struktur_pos
		{
			get
			{
				return this._struktur_pos;
			}
			set
			{
				if ((this._struktur_pos != value))
				{
					this._struktur_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht_pos", DbType="SmallInt NOT NULL")]
		public short beschicht_pos
		{
			get
			{
				return this._beschicht_pos;
			}
			set
			{
				if ((this._beschicht_pos != value))
				{
					this._beschicht_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht_typ", DbType="SmallInt NOT NULL")]
		public short beschicht_typ
		{
			get
			{
				return this._beschicht_typ;
			}
			set
			{
				if ((this._beschicht_typ != value))
				{
					this._beschicht_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modell_nr", DbType="SmallInt NOT NULL")]
		public short modell_nr
		{
			get
			{
				return this._modell_nr;
			}
			set
			{
				if ((this._modell_nr != value))
				{
					this._modell_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stufen_flag", DbType="SmallInt NOT NULL")]
		public short stufen_flag
		{
			get
			{
				return this._stufen_flag;
			}
			set
			{
				if ((this._stufen_flag != value))
				{
					this._stufen_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_korrektur_flag", DbType="SmallInt NOT NULL")]
		public short korrektur_flag
		{
			get
			{
				return this._korrektur_flag;
			}
			set
			{
				if ((this._korrektur_flag != value))
				{
					this._korrektur_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teilfert_kz", DbType="SmallInt NOT NULL")]
		public short teilfert_kz
		{
			get
			{
				return this._teilfert_kz;
			}
			set
			{
				if ((this._teilfert_kz != value))
				{
					this._teilfert_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serien_kz", DbType="SmallInt NOT NULL")]
		public short serien_kz
		{
			get
			{
				return this._serien_kz;
			}
			set
			{
				if ((this._serien_kz != value))
				{
					this._serien_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opti_flag", DbType="SmallInt NOT NULL")]
		public short opti_flag
		{
			get
			{
				return this._opti_flag;
			}
			set
			{
				if ((this._opti_flag != value))
				{
					this._opti_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text_flag", DbType="SmallInt NOT NULL")]
		public short text_flag
		{
			get
			{
				return this._text_flag;
			}
			set
			{
				if ((this._text_flag != value))
				{
					this._text_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uebermenge_kz", DbType="SmallInt NOT NULL")]
		public short uebermenge_kz
		{
			get
			{
				return this._uebermenge_kz;
			}
			set
			{
				if ((this._uebermenge_kz != value))
				{
					this._uebermenge_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodmenge", DbType="SmallInt NOT NULL")]
		public short prodmenge
		{
			get
			{
				return this._prodmenge;
			}
			set
			{
				if ((this._prodmenge != value))
				{
					this._prodmenge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_austausch_kz", DbType="SmallInt NOT NULL")]
		public short austausch_kz
		{
			get
			{
				return this._austausch_kz;
			}
			set
			{
				if ((this._austausch_kz != value))
				{
					this._austausch_kz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftragsmenge", DbType="SmallInt NOT NULL")]
		public short auftragsmenge
		{
			get
			{
				return this._auftragsmenge;
			}
			set
			{
				if ((this._auftragsmenge != value))
				{
					this._auftragsmenge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otyp", DbType="SmallInt")]
		public System.Nullable<short> otyp
		{
			get
			{
				return this._otyp;
			}
			set
			{
				if ((this._otyp != value))
				{
					this._otyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utyp", DbType="VarChar(10)")]
		public string utyp
		{
			get
			{
				return this._utyp;
			}
			set
			{
				if ((this._utyp != value))
				{
					this._utyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modell_gruppe", DbType="SmallInt NOT NULL")]
		public short modell_gruppe
		{
			get
			{
				return this._modell_gruppe;
			}
			set
			{
				if ((this._modell_gruppe != value))
				{
					this._modell_gruppe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modell_flag", DbType="SmallInt NOT NULL")]
		public short modell_flag
		{
			get
			{
				return this._modell_flag;
			}
			set
			{
				if ((this._modell_flag != value))
				{
					this._modell_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sprossen_flag", DbType="SmallInt NOT NULL")]
		public short sprossen_flag
		{
			get
			{
				return this._sprossen_flag;
			}
			set
			{
				if ((this._sprossen_flag != value))
				{
					this._sprossen_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_nr", DbType="SmallInt NOT NULL")]
		public short logo_nr
		{
			get
			{
				return this._logo_nr;
			}
			set
			{
				if ((this._logo_nr != value))
				{
					this._logo_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_lage", DbType="SmallInt NOT NULL")]
		public short logo_lage
		{
			get
			{
				return this._logo_lage;
			}
			set
			{
				if ((this._logo_lage != value))
				{
					this._logo_lage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_giessharz_flag", DbType="SmallInt NOT NULL")]
		public short o_giessharz_flag
		{
			get
			{
				return this._o_giessharz_flag;
			}
			set
			{
				if ((this._o_giessharz_flag != value))
				{
					this._o_giessharz_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_esg_flag", DbType="SmallInt NOT NULL")]
		public short o_esg_flag
		{
			get
			{
				return this._o_esg_flag;
			}
			set
			{
				if ((this._o_esg_flag != value))
				{
					this._o_esg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_vsg_flag", DbType="SmallInt NOT NULL")]
		public short o_vsg_flag
		{
			get
			{
				return this._o_vsg_flag;
			}
			set
			{
				if ((this._o_vsg_flag != value))
				{
					this._o_vsg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_iso_flag", DbType="SmallInt NOT NULL")]
		public short o_iso_flag
		{
			get
			{
				return this._o_iso_flag;
			}
			set
			{
				if ((this._o_iso_flag != value))
				{
					this._o_iso_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_giessharz_flag", DbType="SmallInt NOT NULL")]
		public short u_giessharz_flag
		{
			get
			{
				return this._u_giessharz_flag;
			}
			set
			{
				if ((this._u_giessharz_flag != value))
				{
					this._u_giessharz_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_esg_flag", DbType="SmallInt NOT NULL")]
		public short u_esg_flag
		{
			get
			{
				return this._u_esg_flag;
			}
			set
			{
				if ((this._u_esg_flag != value))
				{
					this._u_esg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_vsg_flag", DbType="SmallInt NOT NULL")]
		public short u_vsg_flag
		{
			get
			{
				return this._u_vsg_flag;
			}
			set
			{
				if ((this._u_vsg_flag != value))
				{
					this._u_vsg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_bestell_flag", DbType="SmallInt NOT NULL")]
		public short u_bestell_flag
		{
			get
			{
				return this._u_bestell_flag;
			}
			set
			{
				if ((this._u_bestell_flag != value))
				{
					this._u_bestell_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_giessharz_flag", DbType="SmallInt NOT NULL")]
		public short t_giessharz_flag
		{
			get
			{
				return this._t_giessharz_flag;
			}
			set
			{
				if ((this._t_giessharz_flag != value))
				{
					this._t_giessharz_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_esg_flag", DbType="SmallInt NOT NULL")]
		public short t_esg_flag
		{
			get
			{
				return this._t_esg_flag;
			}
			set
			{
				if ((this._t_esg_flag != value))
				{
					this._t_esg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_vsg_flag", DbType="SmallInt NOT NULL")]
		public short t_vsg_flag
		{
			get
			{
				return this._t_vsg_flag;
			}
			set
			{
				if ((this._t_vsg_flag != value))
				{
					this._t_vsg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_iso_flag", DbType="SmallInt NOT NULL")]
		public short t_iso_flag
		{
			get
			{
				return this._t_iso_flag;
			}
			set
			{
				if ((this._t_iso_flag != value))
				{
					this._t_iso_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param1", DbType="VarChar(10)")]
		public string param1
		{
			get
			{
				return this._param1;
			}
			set
			{
				if ((this._param1 != value))
				{
					this._param1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param2", DbType="VarChar(10)")]
		public string param2
		{
			get
			{
				return this._param2;
			}
			set
			{
				if ((this._param2 != value))
				{
					this._param2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param3", DbType="VarChar(10)")]
		public string param3
		{
			get
			{
				return this._param3;
			}
			set
			{
				if ((this._param3 != value))
				{
					this._param3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param4", DbType="VarChar(10)")]
		public string param4
		{
			get
			{
				return this._param4;
			}
			set
			{
				if ((this._param4 != value))
				{
					this._param4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param5", DbType="VarChar(10)")]
		public string param5
		{
			get
			{
				return this._param5;
			}
			set
			{
				if ((this._param5 != value))
				{
					this._param5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param6", DbType="VarChar(10)")]
		public string param6
		{
			get
			{
				return this._param6;
			}
			set
			{
				if ((this._param6 != value))
				{
					this._param6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param7", DbType="VarChar(10)")]
		public string param7
		{
			get
			{
				return this._param7;
			}
			set
			{
				if ((this._param7 != value))
				{
					this._param7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param8", DbType="VarChar(10)")]
		public string param8
		{
			get
			{
				return this._param8;
			}
			set
			{
				if ((this._param8 != value))
				{
					this._param8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param9", DbType="VarChar(10)")]
		public string param9
		{
			get
			{
				return this._param9;
			}
			set
			{
				if ((this._param9 != value))
				{
					this._param9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param10", DbType="VarChar(10)")]
		public string param10
		{
			get
			{
				return this._param10;
			}
			set
			{
				if ((this._param10 != value))
				{
					this._param10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt NOT NULL")]
		public short status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statuszeit", DbType="DateTime NOT NULL")]
		public System.DateTime statuszeit
		{
			get
			{
				return this._statuszeit;
			}
			set
			{
				if ((this._statuszeit != value))
				{
					this._statuszeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschaffungsart", DbType="SmallInt NOT NULL")]
		public short beschaffungsart
		{
			get
			{
				return this._beschaffungsart;
			}
			set
			{
				if ((this._beschaffungsart != value))
				{
					this._beschaffungsart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ae_referenz", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ae_referenz
		{
			get
			{
				return this._ae_referenz;
			}
			set
			{
				if ((this._ae_referenz != value))
				{
					this._ae_referenz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sondertext1", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sondertext1
		{
			get
			{
				return this._sondertext1;
			}
			set
			{
				if ((this._sondertext1 != value))
				{
					this._sondertext1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sondertext2", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sondertext2
		{
			get
			{
				return this._sondertext2;
			}
			set
			{
				if ((this._sondertext2 != value))
				{
					this._sondertext2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sondertext3", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sondertext3
		{
			get
			{
				return this._sondertext3;
			}
			set
			{
				if ((this._sondertext3 != value))
				{
					this._sondertext3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sondertext4", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sondertext4
		{
			get
			{
				return this._sondertext4;
			}
			set
			{
				if ((this._sondertext4 != value))
				{
					this._sondertext4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sondertext5", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sondertext5
		{
			get
			{
				return this._sondertext5;
			}
			set
			{
				if ((this._sondertext5 != value))
				{
					this._sondertext5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artikel_extra1", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string artikel_extra1
		{
			get
			{
				return this._artikel_extra1;
			}
			set
			{
				if ((this._artikel_extra1 != value))
				{
					this._artikel_extra1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artikel_extra2", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string artikel_extra2
		{
			get
			{
				return this._artikel_extra2;
			}
			set
			{
				if ((this._artikel_extra2 != value))
				{
					this._artikel_extra2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonder_kz3", DbType="SmallInt NOT NULL")]
		public short sonder_kz3
		{
			get
			{
				return this._sonder_kz3;
			}
			set
			{
				if ((this._sonder_kz3 != value))
				{
					this._sonder_kz3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_seite", DbType="SmallInt NOT NULL")]
		public short logo_seite
		{
			get
			{
				return this._logo_seite;
			}
			set
			{
				if ((this._logo_seite != value))
				{
					this._logo_seite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lager", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string lager
		{
			get
			{
				return this._lager;
			}
			set
			{
				if ((this._lager != value))
				{
					this._lager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftragsdicke", DbType="Int NOT NULL")]
		public int auftragsdicke
		{
			get
			{
				return this._auftragsdicke;
			}
			set
			{
				if ((this._auftragsdicke != value))
				{
					this._auftragsdicke = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttyp", DbType="SmallInt NOT NULL")]
		public short ttyp
		{
			get
			{
				return this._ttyp;
			}
			set
			{
				if ((this._ttyp != value))
				{
					this._ttyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse1_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse1_text
		{
			get
			{
				return this._b_klasse1_text;
			}
			set
			{
				if ((this._b_klasse1_text != value))
				{
					this._b_klasse1_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse2_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse2_text
		{
			get
			{
				return this._b_klasse2_text;
			}
			set
			{
				if ((this._b_klasse2_text != value))
				{
					this._b_klasse2_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse3_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse3_text
		{
			get
			{
				return this._b_klasse3_text;
			}
			set
			{
				if ((this._b_klasse3_text != value))
				{
					this._b_klasse3_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse4_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse4_text
		{
			get
			{
				return this._b_klasse4_text;
			}
			set
			{
				if ((this._b_klasse4_text != value))
				{
					this._b_klasse4_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse5_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse5_text
		{
			get
			{
				return this._b_klasse5_text;
			}
			set
			{
				if ((this._b_klasse5_text != value))
				{
					this._b_klasse5_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse6_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse6_text
		{
			get
			{
				return this._b_klasse6_text;
			}
			set
			{
				if ((this._b_klasse6_text != value))
				{
					this._b_klasse6_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse7_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse7_text
		{
			get
			{
				return this._b_klasse7_text;
			}
			set
			{
				if ((this._b_klasse7_text != value))
				{
					this._b_klasse7_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_klasse8_text", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string b_klasse8_text
		{
			get
			{
				return this._b_klasse8_text;
			}
			set
			{
				if ((this._b_klasse8_text != value))
				{
					this._b_klasse8_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_tvg_flag", DbType="SmallInt NOT NULL")]
		public short o_tvg_flag
		{
			get
			{
				return this._o_tvg_flag;
			}
			set
			{
				if ((this._o_tvg_flag != value))
				{
					this._o_tvg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_artnr", DbType="Decimal(12,0) NOT NULL")]
		public decimal beschicht1_artnr
		{
			get
			{
				return this._beschicht1_artnr;
			}
			set
			{
				if ((this._beschicht1_artnr != value))
				{
					this._beschicht1_artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_masch", DbType="Int NOT NULL")]
		public int beschicht1_masch
		{
			get
			{
				return this._beschicht1_masch;
			}
			set
			{
				if ((this._beschicht1_masch != value))
				{
					this._beschicht1_masch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_kapa", DbType="Float NOT NULL")]
		public double beschicht1_kapa
		{
			get
			{
				return this._beschicht1_kapa;
			}
			set
			{
				if ((this._beschicht1_kapa != value))
				{
					this._beschicht1_kapa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_pos", DbType="SmallInt NOT NULL")]
		public short beschicht1_pos
		{
			get
			{
				return this._beschicht1_pos;
			}
			set
			{
				if ((this._beschicht1_pos != value))
				{
					this._beschicht1_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_typ", DbType="SmallInt NOT NULL")]
		public short beschicht1_typ
		{
			get
			{
				return this._beschicht1_typ;
			}
			set
			{
				if ((this._beschicht1_typ != value))
				{
					this._beschicht1_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht1_ctrl", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string beschicht1_ctrl
		{
			get
			{
				return this._beschicht1_ctrl;
			}
			set
			{
				if ((this._beschicht1_ctrl != value))
				{
					this._beschicht1_ctrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_artnr", DbType="Decimal(12,0) NOT NULL")]
		public decimal beschicht2_artnr
		{
			get
			{
				return this._beschicht2_artnr;
			}
			set
			{
				if ((this._beschicht2_artnr != value))
				{
					this._beschicht2_artnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_masch", DbType="Int NOT NULL")]
		public int beschicht2_masch
		{
			get
			{
				return this._beschicht2_masch;
			}
			set
			{
				if ((this._beschicht2_masch != value))
				{
					this._beschicht2_masch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_kapa", DbType="Float NOT NULL")]
		public double beschicht2_kapa
		{
			get
			{
				return this._beschicht2_kapa;
			}
			set
			{
				if ((this._beschicht2_kapa != value))
				{
					this._beschicht2_kapa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_pos", DbType="SmallInt NOT NULL")]
		public short beschicht2_pos
		{
			get
			{
				return this._beschicht2_pos;
			}
			set
			{
				if ((this._beschicht2_pos != value))
				{
					this._beschicht2_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_typ", DbType="SmallInt NOT NULL")]
		public short beschicht2_typ
		{
			get
			{
				return this._beschicht2_typ;
			}
			set
			{
				if ((this._beschicht2_typ != value))
				{
					this._beschicht2_typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschicht2_ctrl", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string beschicht2_ctrl
		{
			get
			{
				return this._beschicht2_ctrl;
			}
			set
			{
				if ((this._beschicht2_ctrl != value))
				{
					this._beschicht2_ctrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_laufweg", DbType="Int NOT NULL")]
		public int laufweg
		{
			get
			{
				return this._laufweg;
			}
			set
			{
				if ((this._laufweg != value))
				{
					this._laufweg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearbfolge", DbType="Int NOT NULL")]
		public int bearbfolge
		{
			get
			{
				return this._bearbfolge;
			}
			set
			{
				if ((this._bearbfolge != value))
				{
					this._bearbfolge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_phys_1", DbType="Int NOT NULL")]
		public int mzo_id_phys_1
		{
			get
			{
				return this._mzo_id_phys_1;
			}
			set
			{
				if ((this._mzo_id_phys_1 != value))
				{
					this._mzo_id_phys_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_es_1", DbType="Int NOT NULL")]
		public int mzo_id_es_1
		{
			get
			{
				return this._mzo_id_es_1;
			}
			set
			{
				if ((this._mzo_id_es_1 != value))
				{
					this._mzo_id_es_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_technologie1_1", DbType="Int NOT NULL")]
		public int mzo_technologie1_1
		{
			get
			{
				return this._mzo_technologie1_1;
			}
			set
			{
				if ((this._mzo_technologie1_1 != value))
				{
					this._mzo_technologie1_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_phys_2", DbType="Int NOT NULL")]
		public int mzo_id_phys_2
		{
			get
			{
				return this._mzo_id_phys_2;
			}
			set
			{
				if ((this._mzo_id_phys_2 != value))
				{
					this._mzo_id_phys_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_es_2", DbType="Int NOT NULL")]
		public int mzo_id_es_2
		{
			get
			{
				return this._mzo_id_es_2;
			}
			set
			{
				if ((this._mzo_id_es_2 != value))
				{
					this._mzo_id_es_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_technologie1_2", DbType="Int NOT NULL")]
		public int mzo_technologie1_2
		{
			get
			{
				return this._mzo_technologie1_2;
			}
			set
			{
				if ((this._mzo_technologie1_2 != value))
				{
					this._mzo_technologie1_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_phys_3", DbType="Int NOT NULL")]
		public int mzo_id_phys_3
		{
			get
			{
				return this._mzo_id_phys_3;
			}
			set
			{
				if ((this._mzo_id_phys_3 != value))
				{
					this._mzo_id_phys_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_tvg_flag", DbType="SmallInt NOT NULL")]
		public short u_tvg_flag
		{
			get
			{
				return this._u_tvg_flag;
			}
			set
			{
				if ((this._u_tvg_flag != value))
				{
					this._u_tvg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tvg_flag", DbType="SmallInt NOT NULL")]
		public short t_tvg_flag
		{
			get
			{
				return this._t_tvg_flag;
			}
			set
			{
				if ((this._t_tvg_flag != value))
				{
					this._t_tvg_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_start", DbType="DateTime NOT NULL")]
		public System.DateTime prod_start
		{
			get
			{
				return this._prod_start;
			}
			set
			{
				if ((this._prod_start != value))
				{
					this._prod_start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flaeche", DbType="Float NOT NULL")]
		public double flaeche
		{
			get
			{
				return this._flaeche;
			}
			set
			{
				if ((this._flaeche != value))
				{
					this._flaeche = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_los_flag", DbType="Int NOT NULL")]
		public int los_flag
		{
			get
			{
				return this._los_flag;
			}
			set
			{
				if ((this._los_flag != value))
				{
					this._los_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonderglas", DbType="SmallInt NOT NULL")]
		public short sonderglas
		{
			get
			{
				return this._sonderglas;
			}
			set
			{
				if ((this._sonderglas != value))
				{
					this._sonderglas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonderglas_freigab", DbType="SmallInt NOT NULL")]
		public short sonderglas_freigab
		{
			get
			{
				return this._sonderglas_freigab;
			}
			set
			{
				if ((this._sonderglas_freigab != value))
				{
					this._sonderglas_freigab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etikett_art", DbType="Int NOT NULL")]
		public int etikett_art
		{
			get
			{
				return this._etikett_art;
			}
			set
			{
				if ((this._etikett_art != value))
				{
					this._etikett_art = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etikettnr_count", DbType="Int NOT NULL")]
		public int etikettnr_count
		{
			get
			{
				return this._etikettnr_count;
			}
			set
			{
				if ((this._etikettnr_count != value))
				{
					this._etikettnr_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skizzen_art", DbType="Int NOT NULL")]
		public int skizzen_art
		{
			get
			{
				return this._skizzen_art;
			}
			set
			{
				if ((this._skizzen_art != value))
				{
					this._skizzen_art = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_routelog_id1", DbType="SmallInt NOT NULL")]
		public short routelog_id1
		{
			get
			{
				return this._routelog_id1;
			}
			set
			{
				if ((this._routelog_id1 != value))
				{
					this._routelog_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_routelog_id2", DbType="SmallInt NOT NULL")]
		public short routelog_id2
		{
			get
			{
				return this._routelog_id2;
			}
			set
			{
				if ((this._routelog_id2 != value))
				{
					this._routelog_id2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_routelog_id3", DbType="SmallInt NOT NULL")]
		public short routelog_id3
		{
			get
			{
				return this._routelog_id3;
			}
			set
			{
				if ((this._routelog_id3 != value))
				{
					this._routelog_id3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_fixed", DbType="SmallInt NOT NULL")]
		public short part_fixed
		{
			get
			{
				return this._part_fixed;
			}
			set
			{
				if ((this._part_fixed != value))
				{
					this._part_fixed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_id_es_3", DbType="Int NOT NULL")]
		public int mzo_id_es_3
		{
			get
			{
				return this._mzo_id_es_3;
			}
			set
			{
				if ((this._mzo_id_es_3 != value))
				{
					this._mzo_id_es_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mzo_technologie1_3", DbType="Int NOT NULL")]
		public int mzo_technologie1_3
		{
			get
			{
				return this._mzo_technologie1_3;
			}
			set
			{
				if ((this._mzo_technologie1_3 != value))
				{
					this._mzo_technologie1_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rahmenskizzen_art", DbType="Int NOT NULL")]
		public int rahmenskizzen_art
		{
			get
			{
				return this._rahmenskizzen_art;
			}
			set
			{
				if ((this._rahmenskizzen_art != value))
				{
					this._rahmenskizzen_art = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_anz", DbType="Int NOT NULL")]
		public int bearb_anz
		{
			get
			{
				return this._bearb_anz;
			}
			set
			{
				if ((this._bearb_anz != value))
				{
					this._bearb_anz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_dauer", DbType="Float NOT NULL")]
		public double bearb_dauer
		{
			get
			{
				return this._bearb_dauer;
			}
			set
			{
				if ((this._bearb_dauer != value))
				{
					this._bearb_dauer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearbtiefe_anz", DbType="Int NOT NULL")]
		public int bearbtiefe_anz
		{
			get
			{
				return this._bearbtiefe_anz;
			}
			set
			{
				if ((this._bearbtiefe_anz != value))
				{
					this._bearbtiefe_anz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearbtiefe_dauer", DbType="Float NOT NULL")]
		public double bearbtiefe_dauer
		{
			get
			{
				return this._bearbtiefe_dauer;
			}
			set
			{
				if ((this._bearbtiefe_dauer != value))
				{
					this._bearbtiefe_dauer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearbfertig_anz", DbType="Int NOT NULL")]
		public int bearbfertig_anz
		{
			get
			{
				return this._bearbfertig_anz;
			}
			set
			{
				if ((this._bearbfertig_anz != value))
				{
					this._bearbfertig_anz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearbfertig_dauer", DbType="Float NOT NULL")]
		public double bearbfertig_dauer
		{
			get
			{
				return this._bearbfertig_dauer;
			}
			set
			{
				if ((this._bearbfertig_dauer != value))
				{
					this._bearbfertig_dauer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftnr_pos", DbType="VarChar(20)")]
		public string auftnr_pos
		{
			get
			{
				return this._auftnr_pos;
			}
			set
			{
				if ((this._auftnr_pos != value))
				{
					this._auftnr_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheibnr_u_oteil", DbType="Int NOT NULL")]
		public int scheibnr_u_oteil
		{
			get
			{
				return this._scheibnr_u_oteil;
			}
			set
			{
				if ((this._scheibnr_u_oteil != value))
				{
					this._scheibnr_u_oteil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teilnr_u_oteil", DbType="Int NOT NULL")]
		public int teilnr_u_oteil
		{
			get
			{
				return this._teilnr_u_oteil;
			}
			set
			{
				if ((this._teilnr_u_oteil != value))
				{
					this._teilnr_u_oteil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stklistentiefe", DbType="Int NOT NULL")]
		public int stklistentiefe
		{
			get
			{
				return this._stklistentiefe;
			}
			set
			{
				if ((this._stklistentiefe != value))
				{
					this._stklistentiefe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anz_bearb", DbType="Int NOT NULL")]
		public int anz_bearb
		{
			get
			{
				return this._anz_bearb;
			}
			set
			{
				if ((this._anz_bearb != value))
				{
					this._anz_bearb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etiketten_erzeugt", DbType="SmallInt NOT NULL")]
		public short etiketten_erzeugt
		{
			get
			{
				return this._etiketten_erzeugt;
			}
			set
			{
				if ((this._etiketten_erzeugt != value))
				{
					this._etiketten_erzeugt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skizzen_erzeugt", DbType="SmallInt NOT NULL")]
		public short skizzen_erzeugt
		{
			get
			{
				return this._skizzen_erzeugt;
			}
			set
			{
				if ((this._skizzen_erzeugt != value))
				{
					this._skizzen_erzeugt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rskizzen_erzeugt", DbType="SmallInt NOT NULL")]
		public short rskizzen_erzeugt
		{
			get
			{
				return this._rskizzen_erzeugt;
			}
			set
			{
				if ((this._rskizzen_erzeugt != value))
				{
					this._rskizzen_erzeugt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cu_id", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string cu_id
		{
			get
			{
				return this._cu_id;
			}
			set
			{
				if ((this._cu_id != value))
				{
					this._cu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschaffungsart0", DbType="SmallInt NOT NULL")]
		public short beschaffungsart0
		{
			get
			{
				return this._beschaffungsart0;
			}
			set
			{
				if ((this._beschaffungsart0 != value))
				{
					this._beschaffungsart0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entschicht_id", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string entschicht_id
		{
			get
			{
				return this._entschicht_id;
			}
			set
			{
				if ((this._entschicht_id != value))
				{
					this._entschicht_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bestell_id", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string bestell_id
		{
			get
			{
				return this._bestell_id;
			}
			set
			{
				if ((this._bestell_id != value))
				{
					this._bestell_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdefertig", DbType="SmallInt NOT NULL")]
		public short bdefertig
		{
			get
			{
				return this._bdefertig;
			}
			set
			{
				if ((this._bdefertig != value))
				{
					this._bdefertig = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdestueckoffen_anz", DbType="SmallInt NOT NULL")]
		public short bdestueckoffen_anz
		{
			get
			{
				return this._bdestueckoffen_anz;
			}
			set
			{
				if ((this._bdestueckoffen_anz != value))
				{
					this._bdestueckoffen_anz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdebearb_anz", DbType="SmallInt NOT NULL")]
		public short bdebearb_anz
		{
			get
			{
				return this._bdebearb_anz;
			}
			set
			{
				if ((this._bdebearb_anz != value))
				{
					this._bdebearb_anz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschich", DbType="Int NOT NULL")]
		public int beschich
		{
			get
			{
				return this._beschich;
			}
			set
			{
				if ((this._beschich != value))
				{
					this._beschich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stufen_ref", DbType="Int NOT NULL")]
		public int stufen_ref
		{
			get
			{
				return this._stufen_ref;
			}
			set
			{
				if ((this._stufen_ref != value))
				{
					this._stufen_ref = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glas_id", DbType="Int NOT NULL")]
		public int glas_id
		{
			get
			{
				return this._glas_id;
			}
			set
			{
				if ((this._glas_id != value))
				{
					this._glas_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_glas_id10", DbType="Int NOT NULL")]
		public int glas_id10
		{
			get
			{
				return this._glas_id10;
			}
			set
			{
				if ((this._glas_id10 != value))
				{
					this._glas_id10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vielfachheit", DbType="SmallInt NOT NULL")]
		public short vielfachheit
		{
			get
			{
				return this._vielfachheit;
			}
			set
			{
				if ((this._vielfachheit != value))
				{
					this._vielfachheit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spalten", DbType="SmallInt NOT NULL")]
		public short spalten
		{
			get
			{
				return this._spalten;
			}
			set
			{
				if ((this._spalten != value))
				{
					this._spalten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bde_serie", DbType="Int NOT NULL")]
		public int bde_serie
		{
			get
			{
				return this._bde_serie;
			}
			set
			{
				if ((this._bde_serie != value))
				{
					this._bde_serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mindermenge", DbType="Int NOT NULL")]
		public int mindermenge
		{
			get
			{
				return this._mindermenge;
			}
			set
			{
				if ((this._mindermenge != value))
				{
					this._mindermenge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menge_nach", DbType="Int NOT NULL")]
		public int menge_nach
		{
			get
			{
				return this._menge_nach;
			}
			set
			{
				if ((this._menge_nach != value))
				{
					this._menge_nach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mindermenge_nach", DbType="Int NOT NULL")]
		public int mindermenge_nach
		{
			get
			{
				return this._mindermenge_nach;
			}
			set
			{
				if ((this._mindermenge_nach != value))
				{
					this._mindermenge_nach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freigabe_teil0", DbType="SmallInt NOT NULL")]
		public short freigabe_teil0
		{
			get
			{
				return this._freigabe_teil0;
			}
			set
			{
				if ((this._freigabe_teil0 != value))
				{
					this._freigabe_teil0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merke_beschaffung", DbType="SmallInt NOT NULL")]
		public short merke_beschaffung
		{
			get
			{
				return this._merke_beschaffung;
			}
			set
			{
				if ((this._merke_beschaffung != value))
				{
					this._merke_beschaffung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gewicht_rechteck", DbType="Float NOT NULL")]
		public double gewicht_rechteck
		{
			get
			{
				return this._gewicht_rechteck;
			}
			set
			{
				if ((this._gewicht_rechteck != value))
				{
					this._gewicht_rechteck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieferant", DbType="Int NOT NULL")]
		public int lieferant
		{
			get
			{
				return this._lieferant;
			}
			set
			{
				if ((this._lieferant != value))
				{
					this._lieferant = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
